### ISSUE TITLE
单角度环PID控制器 无法控制 Yaw角 归零

### ISSUE THREAD

**Issue by xxyyttxx** [UESTC404/Quadcopter#12]
曾经推测：与电机的增益关系弄反了。
结果：修改代码没有起作用。

其中有一次测试现象：会有反馈，但是会维持在非期望值处。

怀疑是DMP解算Yaw漂移。

**Comment by xxyyttxx** [comment]
PID理应归零啊（期望0

**Comment by daisenryaku** [comment]
与电机的增益关系搞反了

**Comment by xxyyttxx** [comment]
![default](https://user-images.githubusercontent.com/25104011/34729050-9a0a52fc-f596-11e7-8c46-853ce6b2ecd9.jpg)
