### ISSUE TITLE
CMSIS DSP库 PID-API 文档

### ISSUE THREAD

**Issue by xxyyttxx** [UESTC404/Quadcopter#3]
[CMSIS DSP库 PID-API 文档](http://arm-software.github.io/CMSIS_5/DSP/html/group__PID.html)

**Comment by xxyyttxx** [comment]
## 描述
比例积分微分（PID）控制器是一种通用（且最常用）的闭环反馈的控制机制，在工业控制系统中广泛使用。 
```
y[n] = y[n-1] + A0 * x[n] + A1 * x[n-1] + A2 * x[n-2]
A0 = Kp + Ki + Kd
A1 = (-Kp ) - (2 * Kd )
A2 = Kd
其中Kp是比例常数， Ki是积分常数， Kd是微分常数
```
PID控制器计算“误差”值error（测量值和参考值之间的差值）。 控制器尝试通过调整过程控制输入来最小化error。 比例值决定对当前error的反馈程度（reaction），积分值根据最近error的总和确定反馈程度，导数值根据error变化的速率确定反馈程度。

## API
这组函数实现了用于Q15，Q31和浮点数据类型的PID控制器。 这些函数对单个数据样本进行操作，每次调用该函数都会返回一个单独的处理值。 S指向PID控制数据结构的一个实例。 in是输入采样值。 这些函数返回输出值。
### 实例结构 `arm_pid_instance_xxx *S`
实例数据结构存储着PID控制器的增益参数A0，A1，A2以及一些状态变量（会在控制中变化的值，因此实例结构不能放在常量数据部分，建议使用初始化函数）。必须为每个PID控制器定义一个单独的实例结构。 对于3种支持的数据类型，都有单独的实例结构声明。
### 重置功能
对于清除状态数组的每个数据类型还有一个相关的复位功能。

**Comment by daisenryaku** [comment]
一份熟代码：

[uav_control.cpp](https://github.com/TianfaYao/ADRC_AutoQuadrotor/blob/master/1.code/uav/uav_control.cpp)

[uav_pid.cpp](https://github.com/TianfaYao/ADRC_AutoQuadrotor/blob/master/1.code/uav/uav_pid.cpp)
