### ISSUE TITLE
添加HMC5883驱动

### ISSUE THREAD

**Issue by daisenryaku** [UESTC404/Quadcopter#4]
## HMC5883介绍
三轴磁力计，也叫电子罗盘，数字指南针，能利用地磁场来定北极。

## 为什么要用HMC5883？
+ 一句话：校正YAW

+ YAW轴比较特殊，因为偏航角法线方向刚好和地球重力平行，这个方向的角度无法由加速度计直接测得，需要增加一个电子罗盘来替代加速度计。

+ 如果不使用罗盘的话，我们可以单纯的通过角速度积分来测得偏航角，缺点是由于积分环节中存在积分漂移，偏航角随着时间的推移会偏差越来越大，就会出现航向角漂移的问题（体现为原地旋转）。

+ 详细说明点[这里](http://www.crazepony.com/book/wiki/algorithm-pid.html)

## 移植参考代码
[HMC5883L.h](https://github.com/Crazepony/crazepony-firmware-none/blob/master/HardWareDriver/H/HMC5883L.h)
[HMC5883L.c](https://github.com/Crazepony/crazepony-firmware-none/blob/master/HardWareDriver/C/HMC5883L.c)

## 使用可能存在的坑
1.  [四轴磁力计HMC5883计算航偏角](http://blog.sina.com.cn/s/blog_154d272c90102x0h7.html)，当磁力计的X轴指南Z轴朝下时为标准方向！
 
2.  地磁的干扰，要远离大电流的元件和线路，要校准。

3. [磁力计的校准：具体步骤是全方位720度旋转（整体旋转就像一个球一样旋转）。在上位机内记录磁力计数据写入到Excel表格内，然后最大值加最小值除以2，然后在磁力计原始数据上减去这个值（x,y,z）,这样就可以大致消除磁力计影响](http://www.tk4479.net/williamgavin/article/details/76685789)

## PS
MPU9150已经把电子罗盘功能也整合在片上了，为什么要用MPU6050 + HMC5883?

**Comment by daisenryaku** [comment]
[GY85使用](http://blog.csdn.net/github_30605157/article/details/65006527)
angle=atan2((double)y,(double)x)*(180/3.1416)+180

**Comment by xxyyttxx** [comment]
## 解算YAW！

- [x] 工程代码风格
- [ ] 工程结构整理
- [ ] 电子罗盘的Z映射 + 六面校准（椭球校正）
- [x] 电子罗盘标定写死在程序里
- [ ] question: `range_trans(3000-u16Rcvr_ch4, max_rate_pr)`
---
电子罗盘 地磁计 校准
[知乎 椭球校准](https://www.zhihu.com/question/20944506/answer/16680600)
[知乎 椭球校准2](https://www.zhihu.com/question/20944506/answer/229365048)
[磁力计校准背景知识](http://www.dzsc.com/data/html/2010-11-29/87454.html)

**Comment by xxyyttxx** [comment]
![screen shot 2018-01-03 at 3 32 19 pm](https://user-images.githubusercontent.com/25104011/34512150-576999ee-f09b-11e7-8f12-cb44bb52c46d.png)
![screen shot 2018-01-03 at 3 44 08 pm](https://user-images.githubusercontent.com/25104011/34512364-fa883bde-f09c-11e7-8fdf-5d74400e8244.png)
瞎搞了一个正交椭球拟合..视觉二分调整..
然而烧录进去的时候，读数突变。。。

**Comment by xxyyttxx** [comment]
重新弄了一些数据，并重建了一个模型。
如图
![screen shot 2018-01-03 at 6 46 13 pm](https://user-images.githubusercontent.com/25104011/34518164-2800bdd6-f0b9-11e7-82f4-02c9e13e86de.png)
![screen shot 2018-01-03 at 6 46 08 pm](https://user-images.githubusercontent.com/25104011/34518166-294f454a-f0b9-11e7-9c3f-d5e4b897a485.png)
数据文档如下：
[Archive.zip](https://github.com/UESTC404/Quadcopter/files/1600126/Archive.zip)
